### ISSUE TITLE
FindPostgreSQL.cmake

### ISSUE THREAD

**Issue by hbustos** [iachievedit/build_openvas#1]
Hi, I have a question: How do I run this file?

thanks

**Comment by iachievedit** [comment]
`FindPostgreSQL.cmake` itself is not executed by this repository but patched in:  see `scripts/11_gvmd.sh`.

**Comment by hbustos** [comment]
> `FindPostgreSQL.cmake` itself is not executed by this repository but patched in: see `scripts/11_gvmd.sh`.

Exelent, works for my, I have to install libglib2.0-dev and run the script , thanks a lot.
